# Generated by Django 3.1.6 on 2021-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('CPU', models.TextField(max_length=100)),
                ('RAM', models.CharField(max_length=50)),
                ('GPU', models.TextField(max_length=100)),
                ('HDD', models.TextField(max_length=100)),
                ('OS', models.TextField(max_length=50)),
            ],
        ),
    ]
