# Generated by Django 3.1.6 on 2021-02-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReqApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='OS',
            field=models.TextField(max_length=100),
        ),
    ]
