# Generated by Django 3.1.6 on 2021-02-06 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ReqApp', '0002_auto_20210205_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
    ]
